### PR TITLE
Tracking info update

### PR DESCRIPTION
**Pull request by chubibest**
This documents the new flow for adding tracking and fulfilment info to an order

### CODE REVIEW

**Comment by surgieboi** [comment]
@chubibest in Schema, can you update the menu item styling to be normal casing vs. upper?

**Comment by chubibest** [comment]
@thatotherkid86 Done

**Review by Phunmbi — APPROVED** [review]
🔥👍🏾

**Review by omoefe-dukuye — APPROVED** [review]
LGTM

**Pull request merged**
